// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGKZbUONUwVFEgeWFZ6ZtxAMFKLblipA',
    appId: '1:554891898209:web:92ff0398154e5a997b2920',
    messagingSenderId: '554891898209',
    projectId: 'zidallieappproj',
    authDomain: 'zidallieappproj.firebaseapp.com',
    databaseURL: 'https://zidallieappproj-default-rtdb.firebaseio.com',
    storageBucket: 'zidallieappproj.appspot.com',
    measurementId: 'G-QL87SC5T4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoB_goiXjsZhZg_FgLBQY30eeJRTXvEgY',
    appId: '1:554891898209:android:9213e440598d9ac17b2920',
    messagingSenderId: '554891898209',
    projectId: 'zidallieappproj',
    databaseURL: 'https://zidallieappproj-default-rtdb.firebaseio.com',
    storageBucket: 'zidallieappproj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC58yN16BHG0ExFxT3FtHYnHJQ0bAmBBdk',
    appId: '1:554891898209:ios:17b45591fef07ccd7b2920',
    messagingSenderId: '554891898209',
    projectId: 'zidallieappproj',
    databaseURL: 'https://zidallieappproj-default-rtdb.firebaseio.com',
    storageBucket: 'zidallieappproj.appspot.com',
    iosClientId: '554891898209-c9gbvkap0s6p6ribbinoajrnf7makqql.apps.googleusercontent.com',
    iosBundleId: 'com.example.tester',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC58yN16BHG0ExFxT3FtHYnHJQ0bAmBBdk',
    appId: '1:554891898209:ios:17b45591fef07ccd7b2920',
    messagingSenderId: '554891898209',
    projectId: 'zidallieappproj',
    databaseURL: 'https://zidallieappproj-default-rtdb.firebaseio.com',
    storageBucket: 'zidallieappproj.appspot.com',
    iosClientId: '554891898209-c9gbvkap0s6p6ribbinoajrnf7makqql.apps.googleusercontent.com',
    iosBundleId: 'com.example.tester',
  );
}
